### ISSUE TITLE
移动排序提示错误

### ISSUE THREAD

**Issue by gyp719** [pstldz/dcat-admin-grid-sotrable#1]
[2023-10-26 20:27:11] local.ERROR: Class name must be a valid object or a string {"exception":"[object] (Error(code: 0): Class name must be a valid object or a string at /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Repositories/EloquentRepository.php:737)
[stacktrace]
#0 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Repositories/EloquentRepository.php(728): Dcat\\Admin\\Repositories\\EloquentRepository->createModel()
#1 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Repositories/EloquentRepository.php(83): Dcat\\Admin\\Repositories\\EloquentRepository->model()
#2 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Repositories/EloquentRepository.php(60): Dcat\\Admin\\Repositories\\EloquentRepository->initModel()
#3 /home/vagrant/Code/Tools/vendor/pstldz/dcat-admin-grid-sotrable/src/SaveOrderButton.php(45): Dcat\\Admin\\Repositories\\EloquentRepository->__construct()
#4 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): Pstldz\\DcatAdminGridSotrable\\SaveOrderButton->Pstldz\\DcatAdminGridSotrable\\{closure}()
#5 /home/vagrant/Code/Tools/vendor/pstldz/dcat-admin-grid-sotrable/src/SaveOrderButton.php(49): Illuminate\\Support\\Collection->each()
#6 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Controllers/HandleActionController.php(25): Pstldz\\DcatAdminGridSotrable\\SaveOrderButton->handle()
#7 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Dcat\\Admin\\Http\\Controllers\\HandleActionController->handle()
#8 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#9 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#10 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#11 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#12 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/WebUploader.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\WebUploader->handle()
#14 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/Session.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\Session->handle()
#16 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/Permission.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\Permission->handle()
#18 /home/vagrant/Code/Tools/vendor/de-memory/lock-screen/src/Http/Middleware/LockScreen.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): DeMemory\\LockScreen\\Http\\Middleware\\LockScreen->handle()
#20 /home/vagrant/Code/Tools/dcat-admin-extensions/dcat-admin/operation-log/src/Http/Middleware/LogOperation.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\OperationLog\\Http\\Middleware\\LogOperation->handle()
#22 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/Bootstrap.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\Bootstrap->handle()
#24 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/Pjax.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\Pjax->handle()
#26 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/Authenticate.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\Authenticate->handle()
#28 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#30 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(159): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(135): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#32 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(87): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#33 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#34 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#36 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#38 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#40 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#41 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#43 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#45 /home/vagrant/Code/Tools/vendor/dcat/laravel-admin/src/Http/Middleware/Application.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Dcat\\Admin\\Http\\Middleware\\Application->handle()
#47 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(800): Illuminate\\Pipeline\\Pipeline->then()
#49 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#50 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#51 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#52 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#53 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#54 /home/vagrant/Code/Tools/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#56 /home/vagrant/Code/Tools/app/Http/Middleware/ValidateRequestParamsMiddleware.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\ValidateRequestParamsMiddleware->handle()
#58 /home/vagrant/Code/Tools/app/Http/Middleware/TraceRequestId.php(35): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\TraceRequestId->handle()
#60 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#62 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#63 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#65 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#66 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#68 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#70 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#72 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#74 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#76 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#77 /home/vagrant/Code/Tools/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#78 {main}
"}

**Comment by abyssgoing** [comment]
我刚也遇到这个问题，把使用模型改成使用数据仓库，看代码是以数据仓库来开发的。

**Comment by gyp719** [comment]
> 我刚也遇到这个问题，把使用模型改成使用数据仓库，看代码是以数据仓库来开发的。

感谢， 用数据仓库 来开发进行排序， 没有报错， 但是感觉排序有点不对， 将其中一条拖到最上面， 并没有按照预期的结果排序， 数据有些紊乱

**Comment by ljyljy0211** [comment]
> > 我刚也遇到这个问题，把使用模型改成使用数据仓库，看代码是以数据仓库来开发的。
> 
> 感谢， 用数据仓库 来开发进行排序， 没有报错， 但是感觉排序有点不对， 将其中一条拖到最上面， 并没有按照预期的结果排序， 数据有些紊乱

需要你的sort字段原来就不能重复，所以需要改下原来字段的值

**Comment by gyp719** [comment]
> > > 我刚也遇到这个问题，把使用模型改成使用数据仓库，看代码是以数据仓库来开发的。
> > 
> > 
> > 感谢， 用数据仓库 来开发进行排序， 没有报错， 但是感觉排序有点不对， 将其中一条拖到最上面， 并没有按照预期的结果排序， 数据有些紊乱
> 
> 需要你的sort字段原来就不能重复，所以需要改下原来字段的值

确实如此， 已解决。感谢。
